const DEFAULT_MAX_TARGETS = 20;
const DEFAULT_MAX_FIELDS = 12;
const DEFAULT_MAX_HOVER_REGIONS = 8;
const DEFAULT_MAX_FINDINGS = 20;

export function generatePlaywrightSpec(scan, options = {}) {
  const targets = selectExportTargets(scan, options);
  const title = safeSingleLine(options.title || `PALS generated audit: ${scan?.url || "scan"}`);
  const lines = [
    `import { test, expect } from "@playwright/test";`,
    "",
    "// Generated by PALS from active pointer scanning data.",
    "// Review selectors and TODO findings before adding this spec to a gated suite.",
    "",
    `test(${jsString(title)}, async ({ page }) => {`,
    `  await page.goto(${jsString(scan?.url || "about:blank")});`,
    `  await expect(page.locator("body")).toBeVisible();`,
    "",
  ];

  appendInteractiveTargets(lines, targets.interactive);
  appendFieldTargets(lines, targets.fields);
  appendHoverRegions(lines, targets.hoverRegions);
  appendFindings(lines, targets.findings);

  lines.push("});", "");
  return lines.join("\n");
}

export function selectExportTargets(scan, options = {}) {
  const maxTargets = positiveInteger(options.maxTargets, DEFAULT_MAX_TARGETS);
  const maxFields = positiveInteger(options.maxFields, DEFAULT_MAX_FIELDS);
  const maxHoverRegions = positiveInteger(
    options.maxHoverRegions,
    DEFAULT_MAX_HOVER_REGIONS
  );
  const maxFindings = positiveInteger(options.maxFindings, DEFAULT_MAX_FINDINGS);
  const semantic = scan?.semantic || {};

  return {
    interactive: uniqueByLocator(
      sortExportCandidates((semantic.interactive || []).filter(isExportableElement))
    ).slice(0, maxTargets),
    fields: uniqueByLocator(
      sortExportCandidates((semantic.fields || []).filter(isExportableElement))
    ).slice(0, Math.min(maxFields, maxTargets)),
    hoverRegions: (scan?.regions || [])
      .filter((region) => region?.type === "dynamic-hover")
      .filter((region) => region.bounds || region.hoverAdded?.length || region.hoverRemoved?.length)
      .slice(0, maxHoverRegions),
    findings: (scan?.findings?.items || []).slice(0, maxFindings),
  };
}

function appendInteractiveTargets(lines, interactive) {
  if (!interactive.length) return;

  lines.push(`  await test.step("PALS semantic controls", async () => {`);
  for (const target of interactive) {
    const locator = locatorExpression(target);
    const label = targetLabel(target);
    lines.push(
      `    await expect(${locator}, ${jsString(`PALS target: ${label}`)}).toBeVisible();`
    );
  }
  lines.push("  });", "");
}

function appendFieldTargets(lines, fields) {
  if (!fields.length) return;

  lines.push(`  await test.step("PALS form fields", async () => {`);
  for (const field of fields) {
    const locator = fieldLocatorExpression(field);
    const label = targetLabel(field);
    lines.push(
      `    await expect(${locator}, ${jsString(`PALS field: ${label}`)}).toBeVisible();`
    );
  }
  lines.push("  });", "");
}

function appendHoverRegions(lines, hoverRegions) {
  if (!hoverRegions.length) return;

  lines.push(`  await test.step("PALS hover-discovered regions", async () => {`);
  for (const region of hoverRegions) {
    const point = regionCenter(region);
    if (point) {
      lines.push(`    await page.mouse.move(${formatNumber(point.x)}, ${formatNumber(point.y)});`);
      lines.push("    await page.waitForTimeout(80);");
    }

    for (const selector of region.hoverAdded || []) {
      lines.push(`    // PALS hover-added: ${safeComment(selector)}`);
    }
    for (const selector of region.hoverRemoved || []) {
      lines.push(`    // PALS hover-removed: ${safeComment(selector)}`);
    }
  }
  lines.push("  });", "");
}

function appendFindings(lines, findings) {
  if (!findings.length) return;

  lines.push(`  await test.step("PALS findings to review", async () => {`);
  for (const finding of findings) {
    const severity = finding.severity || "unknown";
    const id = finding.id || "PALS-FINDING";
    const category = finding.category || "general";
    const message = finding.message || "Review finding.";
    const selector = finding.selector ? ` Selector: ${safeComment(finding.selector)}.` : "";
    lines.push(
      `    // TODO [${safeComment(severity)}] ${safeComment(id)} ${safeComment(category)}: ${safeComment(message)}${selector}`
    );
  }
  lines.push("  });", "");
}

function locatorExpression(target) {
  const role = normalizeRole(target.role);
  const name = bestAccessibleName(target);
  if (role && name) {
    return `page.getByRole(${jsString(role)}, { name: new RegExp(${jsString(
      escapeRegExp(name)
    )}, "i") }).first()`;
  }

  if (target.selector) {
    return `page.locator(${jsString(target.selector)}).first()`;
  }

  if (role) return `page.getByRole(${jsString(role)}).first()`;
  return `page.locator("body").first()`;
}

function fieldLocatorExpression(field) {
  const label = bestFieldName(field);
  if (label) {
    return `page.getByLabel(new RegExp(${jsString(escapeRegExp(label))}, "i")).first()`;
  }

  const placeholder = safeSingleLine(field.placeholder);
  if (placeholder) {
    return `page.getByPlaceholder(${jsString(placeholder)}).first()`;
  }

  return locatorExpression(field);
}

function targetLabel(target) {
  return (
    bestAccessibleName(target) ||
    safeSingleLine(target.placeholder) ||
    safeSingleLine(target.selector) ||
    safeSingleLine(target.tag) ||
    "unnamed target"
  );
}

function bestAccessibleName(target) {
  return firstNonEmpty([
    target.accessibleName,
    target.label,
    target.text,
    target.title,
    target.placeholder,
  ]);
}

function bestFieldName(field) {
  return firstNonEmpty([field.accessibleName, field.label]);
}

function firstNonEmpty(values) {
  for (const value of values) {
    const text = safeSingleLine(value);
    if (text) return text;
  }
  return "";
}

function isExportableElement(element) {
  if (!element || element.disabled) return false;
  if (!element.selector && !element.role) return false;
  const bounds = element.bounds;
  if (!bounds) return true;
  return Number(bounds.width) > 0 && Number(bounds.height) > 0;
}

function sortExportCandidates(items) {
  return [...items].sort((left, right) => scoreTarget(right) - scoreTarget(left));
}

function scoreTarget(target) {
  let score = 0;
  if (bestAccessibleName(target)) score += 40;
  if (target.role) score += 20;
  if (target.focusable) score += 10;
  if (target.cursor === "pointer") score += 8;
  if (target.tag === "button" || target.role === "button") score += 6;
  if (target.tag === "input" || target.role === "textbox") score += 4;
  return score;
}

function uniqueByLocator(items) {
  const seen = new Set();
  const unique = [];

  for (const item of items) {
    const key = [
      normalizeRole(item.role),
      bestAccessibleName(item).toLowerCase(),
      item.selector || "",
    ].join("|");
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(item);
  }

  return unique;
}

function normalizeRole(role) {
  const value = safeSingleLine(role).toLowerCase();
  if (!value || value === "generic" || value === "presentation") return "";
  return value;
}

function regionCenter(region) {
  const bounds = region.bounds;
  if (!bounds) return null;
  return {
    x: Number(bounds.x) + Number(bounds.width) / 2,
    y: Number(bounds.y) + Number(bounds.height) / 2,
  };
}

function positiveInteger(value, fallback) {
  const number = Number(value);
  return Number.isFinite(number) && number > 0 ? Math.floor(number) : fallback;
}

function safeSingleLine(value) {
  return String(value || "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120);
}

function safeComment(value) {
  return safeSingleLine(value).replace(/\*\//g, "* /");
}

function escapeRegExp(value) {
  return String(value).replace(/[\\^$.*+?()[\]{}|]/g, "\\$&");
}

function jsString(value) {
  return JSON.stringify(String(value));
}

function formatNumber(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) return "0";
  return String(Math.round(number * 100) / 100);
}
